//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drawing()
        {
            this.Drawings1 = new HashSet<Drawing>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Canvas { get; set; }
        public bool Remixed { get; set; }
        public Nullable<int> RemixedID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Publicity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drawing> Drawings1 { get; set; }
        public virtual Drawing Drawing1 { get; set; }
        public virtual User User { get; set; }
    }
}
