//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawing
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Canvas { get; set; }
        public bool Remixed { get; set; }
        public Nullable<int> RemixedID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Publicity { get; set; }
        public string CanvasSVG { get; set; }
    
        public virtual User User { get; set; }
    }
}
